# -*- coding: utf-8 -*-
"""SimuladoAnderson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P4ACPRtCD17tpBUy640_3iAJ1irSKW-o
"""

def q1(n: float) -> str:
  if n > 0:
    return "Positivo"
  elif n < 0:
    return "Negativo"
  else:
    return "Zero"

def q2(n: float) -> str:
  if n % 2 == 0:
    return "Par"
  else:
    return "Ímpar"

def q3(n: int) -> str:
  if n < 18:
    return "Menor de idade"
  elif n < 60:
    return "Adulto"
  else:
    return "Idoso"

def q4(n1: float, n2: float) -> float:
  if n1 > n2:
    return n1
  else:
    return n2

def q5(n1: float, n2: float, n3: float) -> float:
  tupla = (n1, n2, n3)
  maior = n1
  for i in tupla:
    if i > maior:
      maior = i
  return maior

def q6(nota: float) -> str:
  if nota >= 9:
    return 'A'
  elif nota >= 7:
    return 'B'
  elif nota >= 5:
    return 'C'
  else:
    return 'D'

def q7(n: int) -> bool:
  if (n % 3 == 0) and (n % 5 == 0):
    return True
  else:
    return False

def q8(n: float) -> float:
  if n > 2000:
    n += n/10
    return n
  else:
    n += n/20
    return n

def q9(n: float) -> float:
  if n > 100:
    n -= n/10
    return n
  else:
    n -= n/20
    return n

def q10(n1: float, n2: float, o: str) -> float:
  if o not in ('+', '-', '*', '.', 'x', '/'):
    raise Exception("Operador inválido!")
  if (o == '/') and (n2 == 0):
    raise Exception("Divisão por 0!")

  if o == '+':
    return n1 + n2
  elif o == '-':
    return n1 - n2
  elif (o == '*') or (o == '.') or (o == 'x'):
    return n1 * n2
  else:
    return n1 / n2

def q11(n1: float, n2: float, n3: float) -> float:
  tupla = (n1, n2, n3)
  maior = n1
  menor = n1
  for i in tupla:
    if i > maior:
      maior = i
    if i < menor:
      menor = i

  return maior - menor

def q12(a: float, b: float, c: float) -> int:
  delta = (b**2) - (4*a*c)
  if delta < 0:
    return 0
  elif delta == 0:
    return 1
  else:
    return 2

def q13(a: float, b: float, c: float) -> float:
  if a == 0:
    raise Exception("A não pode ser 0!")
  raiz = [0, 0]
  delta = (b**2) - (4*a*c)

  raiz[0] = (-b + (delta**0.5)) / (2*a)
  raiz[1] = (-b - (delta**0.5)) / (2*a)

  return raiz

def q14(a: float, b: float, c: float) -> bool:
  if a == 0:
    return False
  else:
    return True

def q15(a: float, b: float, c: float) -> str:
  delta = (b**2) - (4*a*c)
  if delta < 0:
    return "Não há soluções reais para essa equação"

  raiz = [0, 0]
  raiz[0] = (-b + (delta**0.5)) / (2*a)
  raiz[1] = (-b - (delta**0.5)) / (2*a)

  return "As raízes são " + str(raiz[0]) + " e " + str(raiz[1])

def q16(a: float, b: float, c: float) -> str:
  delta = (b**2) - (4*a*c)
  if delta < 0:
    raise Exception("Não há soluções reais para essa equação")
  elif delta == 0:
    return "As raízes são iguais"
  else:
    return "As raízes são diferentes"

def q17(a: float, b: float, c: float) -> tuple:
  delta = (b**2) - (4*a*c)
  if delta < 0:
    return (delta, None, None)
  x1 = (-b + (delta**0.5)) / (2*a)
  x2 = (-b - (delta**0.5)) / (2*a)
  return (delta, x1, x2)

def q18(a: float, b: float, c: float) -> str:
  if a == 0:
    return "Não é uma equação de segundo grau!"
  if a > 0:
    return "A parábola é voltada para cima!"
  else:
    return "A parábola é voltada para baixo!"

def q19(a: float, b: float, c: float) -> tuple:
  return ((-b/a), (c/a))

def q20(a: float, b: float, c: float) -> str:
  if a == 0:
    raise Exception("A não pode ser 0!")
  delta = (b**2) - (4*a*c)
  x1 = (-b + (delta**0.5)) / (2*a)
  x2 = (-b - (delta**0.5)) / (2*a)
  if x1 == x2:
    return f"O Δ é 0 e as raízes são iguais ({x1})"
  else:
    return f"O Δ é igual a {delta} e as raízes são {x1} e {x2}"